# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 02:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20151227_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Invalid phone number', regex='^\\+?[\\d{1,2}]?\\d{8,16}$')]),
        ),
    ]
